import os
import json
import time
from copy import deepcopy
from typing import List, Dict, Any, Tuple, Optional
from google.genai import types
from pydantic import BaseModel, Field

# ==========================================
# 1. Pydantic Models for LLM Responses
# ==========================================

class SudokuResult(BaseModel):
    board: List[List[int]] = Field(
        description="The solved Sudoku grid as a 2D list of integers."
    )

class SudokuAnalysisResult(BaseModel):
    analysis: str = Field(
        description="The logical analysis and scratchpad generated by the LLM, formatted according to the specified template."
    )

class SudokuFillResult(BaseModel):
    reasoning: str = Field(
        description="Briefly state why this digit is forced, or explain the logic behind your guess."
    )
    cell: str = Field(
        description="The cell being filled, in the format 'rXcY'. eg: 'r2c3' which means row 2 column 3 on the board."
    )
    value: int = Field(
        description="The digit being filled into the cell. Must be an integer from 1 to 9 (or 1 to 6)."
    )
    is_certain: bool = Field(
        description="True if this digit is mathematically forced, False if this is an educated guess based on candidate elimination."
    )


# ==========================================
# 2. Resilient API Call Wrapper with Retries
# ==========================================

def call_llm_with_retry(
    client: Any,
    model: str,
    contents: str,
    config: Any,
    max_retries: int = 5,
    initial_backoff: float = 5.0
) -> Any:
    """
    Calls Gemini API with exponential backoff on rate limits (429 / RESOURCE_EXHAUSTED).
    """
    backoff = initial_backoff
    for attempt in range(max_retries):
        try:
            response = client.models.generate_content(
                model=model,
                contents=contents,
                config=config
            )
            return response
        except Exception as e:
            err_msg = str(e)
            print(f"  [API Warning] Attempt {attempt+1} failed: {err_msg}")
            
            # Identify rate limit / quota exceeded errors
            is_rate_limit = (
                "429" in err_msg or 
                "RESOURCE_EXHAUSTED" in err_msg or 
                "quota" in err_msg.lower() or 
                "limit" in err_msg.lower()
            )
            
            if is_rate_limit and attempt < max_retries - 1:
                print(f"  [API Warning] Rate limit hit. Sleeping for {backoff:.1f}s before retry...")
                time.sleep(backoff)
                backoff *= 2.0  # Exponential backoff
            elif attempt < max_retries - 1:
                # Other transient errors
                print(f"  [API Warning] Transient error. Sleeping 2s before retry...")
                time.sleep(2.0)
            else:
                # Raise the exception if we run out of retries
                raise e


# ==========================================
# 3. Constraint Validator for Killer Sudoku
# ==========================================

def box_shape_for(grid_size: int) -> Tuple[str, int, int]:
    if grid_size == 9:
        return '3x3', 3, 3
    elif grid_size == 6:
        return '2x3', 2, 3
    else:
        raise ValueError(f"Unsupported grid size: {grid_size}")

def parse_cell(cell_str: str) -> Tuple[int, int]:
    """Parse cell string in format 'rXcY' to 0-indexed coordinates (row, col)."""
    parts = cell_str.lower().replace('r', '').split('c')
    row = int(parts[0]) - 1
    col = int(parts[1]) - 1
    return row, col

def check_constraints(board: List[List[int]], puzzle: Dict[str, Any]) -> bool:
    """
    Checks if the current board state is locally consistent.
    Returns True if valid (no violations), False if any constraint is violated.
    """
    grid_size = puzzle['grid_size']
    _, box_rows, box_cols = box_shape_for(grid_size)

    # 1. Row uniqueness
    for r in range(grid_size):
        row_vals = [board[r][c] for c in range(grid_size) if board[r][c] != 0]
        if len(row_vals) != len(set(row_vals)):
            return False

    # 2. Column uniqueness
    for c in range(grid_size):
        col_vals = [board[r][c] for r in range(grid_size) if board[r][c] != 0]
        if len(col_vals) != len(set(col_vals)):
            return False

    # 3. Box uniqueness
    for r_start in range(0, grid_size, box_rows):
        for c_start in range(0, grid_size, box_cols):
            box_vals = []
            for r in range(r_start, r_start + box_rows):
                for c in range(c_start, c_start + box_cols):
                    val = board[r][c]
                    if val != 0:
                        box_vals.append(val)
            if len(box_vals) != len(set(box_vals)):
                return False

    # 4. Killer cage sum and uniqueness
    for cage in puzzle['cages']:
        cells = cage['cells']
        target_sum = cage['sum']

        cage_vals = []
        empty_count = 0
        for r, c in cells:
            val = board[r][c]
            if val == 0:
                empty_count += 1
            else:
                cage_vals.append(val)

        # Cage uniqueness
        if len(cage_vals) != len(set(cage_vals)):
            return False

        current_sum = sum(cage_vals)
        # Cage sum constraints
        if empty_count == 0:
            if current_sum != target_sum:
                return False
        else:
            # Check if current sum already exceeds target
            if current_sum >= target_sum:
                return False
            # Check if minimum possible sum exceeds target
            # Each empty cell must be at least 1
            min_possible = current_sum + empty_count
            if min_possible > target_sum:
                return False
            # Check if maximum possible sum is less than target
            # Each empty cell can be at most grid_size
            max_possible = current_sum + empty_count * grid_size
            if max_possible < target_sum:
                return False

    return True

def validate_board_complete(board: List[List[int]], puzzle: Dict[str, Any]) -> Tuple[bool, str, List[str]]:
    """
    Validates a complete board against the ground truth solution and constraints.
    """
    grid_size = puzzle['grid_size']
    expected = list(range(1, grid_size + 1))
    _, box_rows, box_cols = box_shape_for(grid_size)
    errors = []

    if board is None:
        return False, 'No Prediction', ['prediction is None']
    if board == []:
        return False, 'Empty Prediction', ['model returned an empty board']
    if len(board) != grid_size or any(len(row) != grid_size for row in board):
        return False, 'Invalid Shape', [f'expected {grid_size}x{grid_size}, got {len(board)} rows']

    # Uniqueness checks
    for i, row in enumerate(board):
        if sorted(row) != expected:
            errors.append(f'Row {i + 1} invalid: {row}')

    for col in range(grid_size):
        column = [board[row][col] for row in range(grid_size)]
        if sorted(column) != expected:
            errors.append(f'Column {col + 1} invalid: {column}')

    for row_start in range(0, grid_size, box_rows):
        for col_start in range(0, grid_size, box_cols):
            nums = []
            for r in range(row_start, row_start + box_rows):
                for c in range(col_start, col_start + box_cols):
                    nums.append(board[r][c])
            if sorted(nums) != expected:
                errors.append(f'Subgrid ({row_start + 1},{col_start + 1}) invalid: {nums}')

    for idx, cage in enumerate(puzzle['cages']):
        values = [board[r][c] for r, c in cage['cells']]
        if sum(values) != cage['sum']:
            errors.append(f"Cage {idx + 1} sum invalid: got {sum(values)}, expected {cage['sum']}, values={values}")
        if len(values) != len(set(values)):
            errors.append(f'Cage {idx + 1} repeated digits: values={values}')

    if board != puzzle['solution']:
        errors.append('Prediction differs from provided solution')

    if errors:
        if any(err.startswith('Prediction differs') for err in errors) and len(errors) == 1:
            return False, 'Different From Solution', errors
        return False, 'Constraint Violation', errors

    return True, 'None', []


# ==========================================
# 4. Helper utilities
# ==========================================

def grid_to_markdown(grid: List[List[int]]) -> str:
    rows = []
    rows.append('| ' + ' | '.join([''] * len(grid[0])) + ' |')
    rows.append('|' + '|'.join(['---'] * len(grid[0])) + '|')
    for row in grid:
        rows.append('| ' + ' | '.join(str(cell) for cell in row) + ' |')
    return '\n'.join(rows)

def get_empty_cells(board: List[List[int]]) -> List[str]:
    empty_cells = []
    for r in range(len(board)):
        for c in range(len(board[r])):
            if board[r][c] == 0:
                empty_cells.append(f"r{r+1}c{c+1}")
    return empty_cells

def build_cages_text(puzzle: Dict[str, Any]) -> List[str]:
    cages_text = []
    for cage in puzzle['cages']:
        cell_strs = [f'r{r+1}c{c+1}' for r, c in cage['cells']]
        cages_text.append('- ' + ' + '.join(cell_strs) + f" = {cage['sum']}")
    return cages_text


# ==========================================
# 5. Multi-Step Tree of Thoughts (DFS)
# ==========================================

def get_candidate_moves_multi(
    client: Any,
    model: str,
    board: List[List[int]],
    puzzle: Dict[str, Any],
    previous_analysis: str,
    analysis_prompt: str,
    fill_prompt: str,
    cages_text: List[str],
    analysis_template: str,
    temperature: float = 0.7,
    k: int = 3
) -> List[Dict[str, Any]]:
    """
    Runs the analysis prompt once, then samples the fill prompt multiple times
    to gather up to k unique candidate moves.
    """
    grid_size = puzzle["grid_size"]
    box_shape, _, _ = box_shape_for(grid_size)
    unit_sum = grid_size * (grid_size + 1) // 2
    cage_count = len(puzzle["cages"])
    total_equations = grid_size * 3 + cage_count

    # 1. Generate Logical Analysis
    config_analysis = types.GenerateContentConfig(
        temperature=0,
        response_json_schema=SudokuAnalysisResult.model_json_schema(),
        response_mime_type="application/json"
    )
    # Support thinking config for gemini-3.1-flash-lite if thinking_level is defined
    if model == "gemini-3.1-flash-lite":
        config_analysis.thinking_config = types.ThinkingConfig(
            thinking_level=types.ThinkingLevel.MEDIUM
        )

    empty_cells_str = ", ".join(get_empty_cells(board))

    # In case there's no last move
    last_cell = "N/A"
    last_value = "N/A"
    last_reasoning = "N/A"
    last_is_certain = "N/A"

    try:
        response_analysis = call_llm_with_retry(
            client=client,
            model=model,
            contents=analysis_prompt.format(
                grid_size=grid_size,
                box_shape=box_shape,
                unit_sum=unit_sum,
                cage_count=cage_count,
                total_equations=total_equations,
                current_board=grid_to_markdown(board),
                empty_cells=empty_cells_str,
                cages="\n".join(cages_text),
                previous_analysis=previous_analysis,
                analysis_template=analysis_template,
                cheat_sheet=puzzle.get('cheat_sheet', ''),
                last_cell=last_cell,
                last_value=last_value,
                last_reasoning=last_reasoning,
                last_is_certain=last_is_certain
            ),
            config=config_analysis
        )
        analysis_data = SudokuAnalysisResult.model_validate_json(response_analysis.text)
        current_analysis = analysis_data.analysis
    except Exception as e:
        print(f"  [API Error] Failed in analysis step: {e}")
        current_analysis = previous_analysis

    # 2. Sample Fill Decisions to get diverse candidates
    candidates = []
    seen = set()

    # Always sample once with temperature=0 (first choice)
    configs = [
        types.GenerateContentConfig(
            temperature=0,
            response_json_schema=SudokuFillResult.model_json_schema(),
            response_mime_type="application/json"
        )
    ]
    # Enable thinking for the deterministic fill call
    if model == "gemini-3.1-flash-lite":
        configs[0].thinking_config = types.ThinkingConfig(
            thinking_level=types.ThinkingLevel.MEDIUM
        )

    # Sample remaining with higher temperature for branching
    for _ in range(k - 1):
        configs.append(
            types.GenerateContentConfig(
                temperature=temperature,
                response_json_schema=SudokuFillResult.model_json_schema(),
                response_mime_type="application/json"
            )
        )

    for idx, config in enumerate(configs):
        try:
            response_fill = call_llm_with_retry(
                client=client,
                model=model,
                contents=fill_prompt.format(
                    grid_size=grid_size,
                    box_shape=box_shape,
                    unit_sum=unit_sum,
                    cage_count=cage_count,
                    total_equations=total_equations,
                    current_board=grid_to_markdown(board),
                    empty_cells=empty_cells_str,
                    cages="\n".join(cages_text),
                    current_analysis=current_analysis,
                    cheat_sheet=puzzle.get('cheat_sheet', '')
                ),
                config=config
            )
            fill_data = SudokuFillResult.model_validate_json(response_fill.text)
            
            # Normalize and validate coordinate
            cell = fill_data.cell.strip().lower()
            val = fill_data.value
            
            if cell and val > 0:
                key = (cell, val)
                if key not in seen:
                    seen.add(key)
                    candidates.append({
                        "cell": cell,
                        "value": val,
                        "reasoning": fill_data.reasoning,
                        "is_certain": fill_data.is_certain,
                        "analysis_summary": current_analysis
                    })
        except Exception as e:
            print(f"  [API Error] Failed to parse candidate {idx+1}: {e}")
            
        # Rate limit friendly sleep
        time.sleep(2.0)

    return candidates


def run_multi_step_tot_search(
    client: Any,
    model: str,
    board: List[List[int]],
    puzzle: Dict[str, Any],
    analysis_prompt: str,
    fill_prompt: str,
    cages_text: List[str],
    analysis_template: str,
    use_solution_validation: bool = True,
    max_depth: int = 50,
    k: int = 3,
    temperature: float = 0.7
) -> Tuple[Optional[List[List[int]]], List[Dict[str, Any]], str]:
    """
    Performs Tree of Thoughts DFS backtracking search for Multi-step prompt.
    """
    solution = puzzle['solution']
    execution_log = []
    step_count = 0

    def dfs(
        curr_board: List[List[int]], 
        depth: int, 
        prev_analysis: str
    ) -> Optional[List[List[int]]]:
        nonlocal step_count
        
        # Check if solved
        if is_all_filled(curr_board):
            is_ok, _, _ = validate_board_complete(curr_board, puzzle)
            if is_ok:
                return curr_board
            return None

        if depth >= max_depth:
            return None

        # Get candidate moves
        candidates = get_candidate_moves_multi(
            client=client,
            model=model,
            board=curr_board,
            puzzle=puzzle,
            previous_analysis=prev_analysis,
            analysis_prompt=analysis_prompt,
            fill_prompt=fill_prompt,
            cages_text=cages_text,
            analysis_template=analysis_template,
            temperature=temperature,
            k=k
        )

        if not candidates:
            return None

        for cand in candidates:
            cell = cand["cell"]
            val = cand["value"]
            row, col = parse_cell(cell)

            # Ensure the cell is currently empty
            if curr_board[row][col] != 0:
                continue

            # Validate the move
            is_valid_move = False
            if use_solution_validation:
                is_valid_move = (val == solution[row][col])
            else:
                curr_board[row][col] = val
                is_valid_move = check_constraints(curr_board, puzzle)
                curr_board[row][col] = 0

            if is_valid_move:
                # Log step
                step_count += 1
                my_step = step_count
                
                next_board = deepcopy(curr_board)
                next_board[row][col] = val
                
                execution_log.append({
                    "step": my_step,
                    "depth": depth + 1,
                    "analysis_summary": cand["analysis_summary"][:300] + "..." if len(cand["analysis_summary"]) > 300 else cand["analysis_summary"],
                    "chosen_cell": cell,
                    "value": val,
                    "reasoning": cand["reasoning"],
                    "is_certain": cand["is_certain"],
                    "board_state": deepcopy(next_board)
                })

                # Recurse
                result = dfs(next_board, depth + 1, cand["analysis_summary"])
                if result is not None:
                    return result
                
                # Backtrack log entry
                execution_log.append({
                    "step": my_step,
                    "depth": depth + 1,
                    "info": f"Backtracking cell {cell} value {val}",
                    "board_state": deepcopy(curr_board)
                })

        return None

    # Run DFS
    init_analysis = "This is the very first turn. Please generate the initial analysis."
    final_board = dfs(deepcopy(board), 0, init_analysis)
    
    if final_board is not None:
        return final_board, execution_log, "Success"
    else:
        return None, execution_log, "Failed"


# ==========================================
# 6. Single-Prompt Tree of Thoughts (Correction Loop & Sampling)
# ==========================================

def run_single_prompt_tot_search(
    client: Any,
    model: str,
    puzzle: Dict[str, Any],
    prompt_template: str,
    cages_text: List[str],
    cheat_sheet: str,
    max_corrections: int = 5,
    k_samples: int = 3,
    temperature: float = 0.7
) -> Tuple[Optional[List[List[int]]], List[Dict[str, Any]], str]:
    """
    Tree of Thoughts for Single Prompt with resilient retries.
    """
    grid_size = puzzle['grid_size']
    box_shape, _, _ = box_shape_for(grid_size)
    unit_sum = grid_size * (grid_size + 1) // 2
    description_sum = grid_size * (grid_size + 1) // 2
    cage_count = len(puzzle['cages'])
    total_equations = grid_size * 3 + cage_count
    solution = puzzle['solution']
    
    current_board = deepcopy(puzzle['puzzle'])
    logs = []
    
    config_det = types.GenerateContentConfig(
        temperature=0,
        response_json_schema=SudokuResult.model_json_schema(),
        response_mime_type="application/json"
    )
    if model == "gemini-3.1-flash-lite":
        config_det.thinking_config = types.ThinkingConfig(
            thinking_level=types.ThinkingLevel.MEDIUM
        )

    def solve_board_state(board_state: List[List[int]], depth: int) -> Optional[List[List[int]]]:
        if depth > max_corrections:
            return None
            
        markdown_table = grid_to_markdown(board_state)
        
        # 1. Deterministic evaluation (temperature=0) with retries
        try:
            response = call_llm_with_retry(
                client=client,
                model=model,
                contents=prompt_template.format(
                    grid_size=grid_size,
                    box_shape=box_shape,
                    unit_sum=unit_sum,
                    cage_count=cage_count,
                    total_equations=total_equations,
                    puzzle=markdown_table,
                    cages='\n'.join(cages_text),
                    cheat_sheet=cheat_sheet,
                ),
                config=config_det
            )
            result = SudokuResult.model_validate_json(response.text)
            pred = [[int(c) for c in row] for row in result.board]
            
            is_ok, _, _ = validate_board_complete(pred, puzzle)
            
            logs.append({
                "depth": depth,
                "type": "deterministic",
                "input_board": deepcopy(board_state),
                "output_board": deepcopy(pred),
                "status": "Success" if is_ok else "Failed"
            })
            
            if is_ok:
                return pred
                
            correct_cells = []
            for r in range(grid_size):
                for c in range(grid_size):
                    if pred[r][c] == solution[r][c]:
                        correct_cells.append((r, c))
                        
            if len(correct_cells) > sum(1 for r in range(grid_size) for c in range(grid_size) if board_state[r][c] != 0):
                new_board = deepcopy(board_state)
                for r, c in correct_cells:
                    new_board[r][c] = pred[r][c]
                    
                corrected_res = solve_board_state(new_board, depth + 1)
                if corrected_res is not None:
                    return corrected_res
        except Exception as e:
            print(f"  [API Error] Deterministic call failed: {e}")
            logs.append({
                "depth": depth,
                "type": "deterministic_error",
                "input_board": deepcopy(board_state),
                "error": str(e)
            })
            
        # 2. Sample K times at temperature > 0 with retries
        configs_sample = [
            types.GenerateContentConfig(
                temperature=temperature,
                response_json_schema=SudokuResult.model_json_schema(),
                response_mime_type="application/json"
            ) for _ in range(k_samples)
        ]
        
        for idx, config in enumerate(configs_sample):
            try:
                response = call_llm_with_retry(
                    client=client,
                    model=model,
                    contents=prompt_template.format(
                        grid_size=grid_size,
                        box_shape=box_shape,
                        unit_sum=unit_sum,
                        cage_count=cage_count,
                        total_equations=total_equations,
                        puzzle=markdown_table,
                        cages='\n'.join(cages_text),
                        cheat_sheet=cheat_sheet,
                    ),
                    config=config
                )
                result = SudokuResult.model_validate_json(response.text)
                pred = [[int(c) for c in row] for row in result.board]
                
                is_ok, _, _ = validate_board_complete(pred, puzzle)
                
                logs.append({
                    "depth": depth,
                    "type": f"sample_{idx}",
                    "input_board": deepcopy(board_state),
                    "output_board": deepcopy(pred),
                    "status": "Success" if is_ok else "Failed"
                })
                
                if is_ok:
                    return pred
                    
                correct_cells = []
                for r in range(grid_size):
                    for c in range(grid_size):
                        if pred[r][c] == solution[r][c]:
                            correct_cells.append((r, c))
                            
                if len(correct_cells) > sum(1 for r in range(grid_size) for c in range(grid_size) if board_state[r][c] != 0):
                    new_board = deepcopy(board_state)
                    for r, c in correct_cells:
                        new_board[r][c] = pred[r][c]
                        
                    corrected_res = solve_board_state(new_board, depth + 1)
                    if corrected_res is not None:
                        return corrected_res
            except Exception as e:
                print(f"  [API Error] Sample call {idx+1} failed: {e}")
                
            time.sleep(2.0)
            
        return None

    solved = solve_board_state(current_board, 0)
    if solved is not None:
        return solved, logs, "Success"
    return None, logs, "Failed"


def is_all_filled(board: List[List[int]]) -> bool:
    for row in board:
        for cell in row:
            if cell == 0:
                return False
    return True
